server {
    listen 80;
    
    # Enable Gzip compression for faster loading
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # Crucial for React Router (SPA)
        # If the file isn't found, fallback to index.html instead of a 404 error
        try_files $uri $uri/ /index.html;
    }
}
